const PrismaClient = require('@prisma/client').PrismaClient;

const prisma = new PrismaClient();

async function main() {
  await Promise.all([
    prisma.character_class.createMany({
      data: [
        { class_description: 'Novice' },
        { class_description: 'Swordsman' },
        { class_description: 'Mage' },
        { class_description: 'Archer' },
        { class_description: 'Acolyte' },
        { class_description: 'Merchant' },
        { class_description: 'Thief' },
        { class_description: 'Knight' },
        { class_description: 'Priest' },
        { class_description: 'Wizard' },
        { class_description: 'Blacksmith' },
        { class_description: 'Hunter' },
        { class_description: 'Assassin' },
        { class_description: 'Crusader' },
        { class_description: 'Monk' },
        { class_description: 'Sage' },
        { class_description: 'Rogue' },
        { class_description: 'Alchemist' },
        { class_description: 'Bard' },
        { class_description: 'Dancer' },
        { class_description: 'Wedding' },
        { class_description: 'Super Novice' },
        { class_description: 'Gunslinger' },
        { class_description: 'Ninja' },
        { class_description: 'Xmas' },
        { class_description: 'Summer' },
        { class_description: 'Hanbok' },
        { class_description: 'Oktoberfest' },
        { class_description: 'High Novice' },
        { class_description: 'High Swordsman' },
        { class_description: 'High Mage' },
        { class_description: 'High Archer' },
        { class_description: 'High Acolyte' },
        { class_description: 'High Merchant' },
        { class_description: 'High Thief' },
        { class_description: 'Lord Knight' },
        { class_description: 'High Priest' },
        { class_description: 'High Wizard' },
        { class_description: 'Whitesmith' },
        { class_description: 'Sniper' },
        { class_description: 'Assassin Cross' },
      ],
    }),
    prisma.mob_db.createMany({
      data: [
        {
          id: 1001,
          name_aegis: 'SCORPION',
          name_english: 'Scorpion',
          name_japanese: 'Scorpion',
          level: 24,
          hp: 1109,
          sp: null,
          base_exp: 287,
          job_exp: 176,
          mvp_exp: null,
          attack: 80,
          attack2: 135,
          defense: 30,
          magic_defense: null,
          str: null,
          agi: null,
          vit: 24,
          int: 24,
          dex: 5,
          luk: 52,
          attack_range: 5,
          skill_range: 1,
          chase_range: 10,
          size: 'Small',
          race: 'Insect',
          racegroup_goblin: null,
          racegroup_kobold: null,
          racegroup_orc: null,
          racegroup_golem: null,
          racegroup_guardian: null,
          racegroup_ninja: null,
          racegroup_gvg: null,
          racegroup_battlefield: null,
          racegroup_treasure: null,
          racegroup_biolab: null,
          racegroup_manuk: null,
          racegroup_splendide: null,
          racegroup_scaraba: null,
          racegroup_ogh_atk_def: null,
          racegroup_ogh_hidden: null,
          racegroup_bio5_swordman_thief: null,
          racegroup_bio5_acolyte_merchant: null,
          racegroup_bio5_mage_archer: null,
          racegroup_bio5_mvp: null,
          racegroup_clocktower: null,
          racegroup_thanatos: null,
          racegroup_faceworm: null,
          racegroup_hearthunter: null,
          racegroup_rockridge: null,
          racegroup_werner_lab: null,
          racegroup_temple_demon: null,
          racegroup_illusion_vampire: null,
          racegroup_malangdo: null,
          racegroup_ep172alpha: null,
          racegroup_ep172beta: null,
          racegroup_ep172bath: null,
          element: 'Fire',
          element_level: 1,
          walk_speed: 200,
          attack_delay: 1564,
          attack_motion: 864,
          damage_motion: 576,
          damage_taken: null,
          ai: '09',
          class: null,
          mode_canmove: null,
          mode_looter: null,
          mode_aggressive: null,
          mode_assist: null,
          mode_castsensoridle: null,
          mode_norandomwalk: null,
          mode_nocast: null,
          mode_canattack: null,
          mode_castsensorchase: null,
          mode_changechase: null,
          mode_angry: null,
          mode_changetargetmelee: null,
          mode_changetargetchase: null,
          mode_targetweak: null,
          mode_randomtarget: null,
          mode_ignoremelee: null,
          mode_ignoremagic: null,
          mode_ignoreranged: null,
          mode_mvp: null,
          mode_ignoremisc: null,
          mode_knockbackimmune: null,
          mode_teleportblock: null,
          mode_fixeditemdrop: null,
          mode_detector: null,
          mode_statusimmune: null,
          mode_skillimmune: null,
          mvpdrop1_item: 'Boody_Red',
          mvpdrop1_rate: 70,
          mvpdrop1_option: null,
          mvpdrop1_index: null,
          mvpdrop2_item: null,
          mvpdrop2_rate: null,
          mvpdrop2_option: null,
          mvpdrop2_index: null,
          mvpdrop3_item: "Scorpion's_Tail",
          mvpdrop3_rate: 5500,
          mvpdrop3_option: null,
          mvpdrop3_index: null,
          drop1_item: 'Elunium_Stone',
          drop1_rate: 57,
          drop1_nosteal: null,
          drop1_option: null,
          drop1_index: null,
          drop2_item: null,
          drop2_rate: null,
          drop2_nosteal: null,
          drop2_option: null,
          drop2_index: null,
          drop3_item: 'Solid_Shell',
          drop3_rate: 210,
          drop3_nosteal: null,
          drop3_option: null,
          drop3_index: null,
          drop4_item: 'Fine_Grit',
          drop4_rate: 100,
          drop4_nosteal: null,
          drop4_option: null,
          drop4_index: null,
          drop5_item: 'Yellow_Herb',
          drop5_rate: 200,
          drop5_nosteal: null,
          drop5_option: null,
          drop5_index: null,
          drop6_item: 'Lusty_Iron',
          drop6_rate: 20,
          drop6_nosteal: null,
          drop6_option: null,
          drop6_index: null,
          drop7_item: 'Scorpion_Card',
          drop7_rate: 1,
          drop7_nosteal: 1,
          drop7_option: null,
          drop7_index: null,
          drop8_item: null,
          drop8_rate: null,
          drop8_nosteal: null,
          drop8_option: null,
          drop8_index: null,
          drop9_item: null,
          drop9_rate: null,
          drop9_nosteal: null,
          drop9_option: null,
          drop9_index: null,
          drop10_item: null,
          drop10_rate: null,
          drop10_nosteal: null,
          drop10_option: null,
          drop10_index: null,
        },
        {
          id: 1002,
          name_aegis: 'PORING',
          name_english: 'Poring',
          name_japanese: 'Poring',
          level: 1,
          hp: 50,
          sp: null,
          base_exp: 2,
          job_exp: 1,
          mvp_exp: null,
          attack: 7,
          attack2: 10,
          defense: null,
          magic_defense: 5,
          str: null,
          agi: null,
          vit: null,
          int: null,
          dex: null,
          luk: 6,
          attack_range: 30,
          skill_range: 1,
          chase_range: 10,
          size: 'Medium',
          race: 'Plant',
          racegroup_goblin: null,
          racegroup_kobold: null,
          racegroup_orc: null,
          racegroup_golem: null,
          racegroup_guardian: null,
          racegroup_ninja: null,
          racegroup_gvg: null,
          racegroup_battlefield: null,
          racegroup_treasure: null,
          racegroup_biolab: null,
          racegroup_manuk: null,
          racegroup_splendide: null,
          racegroup_scaraba: null,
          racegroup_ogh_atk_def: null,
          racegroup_ogh_hidden: null,
          racegroup_bio5_swordman_thief: null,
          racegroup_bio5_acolyte_merchant: null,
          racegroup_bio5_mage_archer: null,
          racegroup_bio5_mvp: null,
          racegroup_clocktower: null,
          racegroup_thanatos: null,
          racegroup_faceworm: null,
          racegroup_hearthunter: null,
          racegroup_rockridge: null,
          racegroup_werner_lab: null,
          racegroup_temple_demon: null,
          racegroup_illusion_vampire: null,
          racegroup_malangdo: null,
          racegroup_ep172alpha: null,
          racegroup_ep172beta: null,
          racegroup_ep172bath: null,
          element: 'Water',
          element_level: 1,
          walk_speed: 400,
          attack_delay: 1872,
          attack_motion: 672,
          damage_motion: 480,
          damage_taken: null,
          ai: '02',
          class: null,
          mode_canmove: null,
          mode_looter: null,
          mode_aggressive: null,
          mode_assist: null,
          mode_castsensoridle: null,
          mode_norandomwalk: null,
          mode_nocast: null,
          mode_canattack: null,
          mode_castsensorchase: null,
          mode_changechase: null,
          mode_angry: null,
          mode_changetargetmelee: null,
          mode_changetargetchase: null,
          mode_targetweak: null,
          mode_randomtarget: null,
          mode_ignoremelee: null,
          mode_ignoremagic: null,
          mode_ignoreranged: null,
          mode_mvp: null,
          mode_ignoremisc: null,
          mode_knockbackimmune: null,
          mode_teleportblock: null,
          mode_fixeditemdrop: null,
          mode_detector: null,
          mode_statusimmune: null,
          mode_skillimmune: null,
          mvpdrop1_item: 'Jellopy',
          mvpdrop1_rate: 7000,
          mvpdrop1_option: null,
          mvpdrop1_index: null,
          mvpdrop2_item: 'Knife_',
          mvpdrop2_rate: 100,
          mvpdrop2_option: null,
          mvpdrop2_index: null,
          mvpdrop3_item: null,
          mvpdrop3_rate: null,
          mvpdrop3_option: null,
          mvpdrop3_index: null,
          drop1_item: 'Sticky_Mucus',
          drop1_rate: 400,
          drop1_nosteal: null,
          drop1_option: null,
          drop1_index: null,
          drop2_item: 'Apple',
          drop2_rate: 1000,
          drop2_nosteal: null,
          drop2_option: null,
          drop2_index: null,
          drop3_item: 'Empty_Bottle',
          drop3_rate: 1500,
          drop3_nosteal: null,
          drop3_option: null,
          drop3_index: null,
          drop4_item: 'Apple',
          drop4_rate: 150,
          drop4_nosteal: null,
          drop4_option: null,
          drop4_index: null,
          drop5_item: 'Unripe_Apple',
          drop5_rate: 20,
          drop5_nosteal: null,
          drop5_option: null,
          drop5_index: null,
          drop6_item: 'Poring_Card',
          drop6_rate: 1,
          drop6_nosteal: 1,
          drop6_option: null,
          drop6_index: null,
          drop7_item: null,
          drop7_rate: null,
          drop7_nosteal: null,
          drop7_option: null,
          drop7_index: null,
          drop8_item: null,
          drop8_rate: null,
          drop8_nosteal: null,
          drop8_option: null,
          drop8_index: null,
          drop9_item: null,
          drop9_rate: null,
          drop9_nosteal: null,
          drop9_option: null,
          drop9_index: null,
          drop10_item: null,
          drop10_rate: null,
          drop10_nosteal: null,
          drop10_option: null,
          drop10_index: null,
        },
      ],
    }),
  ]);
}

// execute the main function
main()
  .then(() => console.log('Banco populado com sucesso!'))
  .catch((err) => console.error(err))
  .finally(async () => {
    // close Prisma Client at the end
    await prisma.$disconnect();
  });
