import type { Metadata } from 'next';
import { Exo } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import { envSchema } from '@/config/env.config';
import { Toaster } from '@/components/ui/toaster';
import { TanstackProvider } from '@/providers/tanstack-provider';

import './globals.css';
import { Navbar } from './_components/navbar';

const exo = Exo({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ragnork',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: WithChildren) {
  try {
    const envVars = envSchema.parse(process.env);

    return (
      <ClerkProvider publishableKey={envVars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
        <TanstackProvider>
          <html
            lang="pt-br"
            className="scroll-smooth"
            suppressHydrationWarning={true}
          >
            <body className={exo.className}>
              <main className="w-full min-h-screen relative">
                <Navbar />
                <div className="w-full absolute top-[120px] overflow-x-hidden left-0">
                  {children}
                </div>
              </main>
              <Toaster />
            </body>
          </html>
        </TanstackProvider>
      </ClerkProvider>
    );
  } catch (error) {
    console.error(error);

    return (
      <div>
        <pre>{JSON.stringify(error, null, 2)}</pre>
      </div>
    );
  }
}
