import type { Metadata } from 'next';
import { Exo } from 'next/font/google';

import { envSchema } from '@/config/env.config';
import { Toaster } from '@/components/ui/toaster';
import { TanstackProvider } from '@/providers/tanstack-provider';

import './globals.css';
import { Navbar } from './_components/navbar';
import { getAuthSession } from '@/server/lib/auth.lib';

const exo = Exo({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ragnork',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: WithChildren) {
  try {
    envSchema.parse(process.env);

    const session = await getAuthSession();

    return (
      <TanstackProvider>
        <html
          lang="pt-br"
          className="scroll-smooth"
          suppressHydrationWarning={true}
        >
          <body className={exo.className}>
            <main className="w-full min-h-screen relative">
              <Navbar session={session} />
              <div className="w-full absolute top-[120px] left-0">
                {children}
              </div>
            </main>
            <Toaster />
          </body>
        </html>
      </TanstackProvider>
    );
  } catch (error) {
    console.error(error);

    return <h1>Variaveis de ambiente inválidas</h1>;
  }
}
