-- CreateTable
CREATE TABLE `login` (
    `account_id` VARCHAR(191) NOT NULL,
    `userid` VARCHAR(191) NOT NULL,
    `user_pass` VARCHAR(191) NOT NULL,
    `sex` ENUM('M', 'F', 'S') NOT NULL DEFAULT 'M',
    `email` VARCHAR(191) NOT NULL,
    `group_id` INTEGER NOT NULL DEFAULT 0,
    `state` INTEGER NOT NULL DEFAULT 0,
    `unban_time` INTEGER NOT NULL DEFAULT 0,
    `expiration_time` INTEGER NOT NULL DEFAULT 0,
    `logincount` INTEGER NOT NULL DEFAULT 0,
    `lastlogin` DATETIME(3) NULL,
    `last_ip` VARCHAR(191) NOT NULL,
    `birthdate` DATETIME(3) NULL,
    `character_slots` INTEGER NOT NULL DEFAULT 0,
    `pincode` VARCHAR(191) NOT NULL,
    `pincode_change` INTEGER NOT NULL DEFAULT 0,
    `vip_time` INTEGER NOT NULL DEFAULT 0,
    `old_group` INTEGER NOT NULL DEFAULT 0,
    `web_auth_token` VARCHAR(191) NULL,
    `web_auth_token_enabled` INTEGER NOT NULL DEFAULT 0,
    `discord_id` VARCHAR(191) NOT NULL,
    `last_unique_id` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `login_account_id_key`(`account_id`),
    PRIMARY KEY (`account_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `character_class` (
    `class_id` INTEGER NOT NULL AUTO_INCREMENT,
    `class_description` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`class_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `character` (
    `char_id` INTEGER NOT NULL AUTO_INCREMENT,
    `account_id` INTEGER NOT NULL DEFAULT 0,
    `char_num` INTEGER NOT NULL DEFAULT 0,
    `name` VARCHAR(191) NULL,
    `class` INTEGER NOT NULL,
    `base_level` INTEGER NOT NULL DEFAULT 1,
    `job_level` INTEGER NOT NULL DEFAULT 1,
    `base_exp` BIGINT NOT NULL DEFAULT 0,
    `job_exp` BIGINT NOT NULL DEFAULT 0,
    `zeny` INTEGER NOT NULL DEFAULT 0,
    `str` INTEGER NOT NULL DEFAULT 0,
    `agi` INTEGER NOT NULL DEFAULT 0,
    `vit` INTEGER NOT NULL DEFAULT 0,
    `int` INTEGER NOT NULL DEFAULT 0,
    `dex` INTEGER NOT NULL DEFAULT 0,
    `luk` INTEGER NOT NULL DEFAULT 0,
    `pow` INTEGER NOT NULL DEFAULT 0,
    `sta` INTEGER NOT NULL DEFAULT 0,
    `wis` INTEGER NOT NULL DEFAULT 0,
    `spl` INTEGER NOT NULL DEFAULT 0,
    `con` INTEGER NOT NULL DEFAULT 0,
    `crt` INTEGER NOT NULL DEFAULT 0,
    `max_hp` INTEGER NOT NULL DEFAULT 0,
    `hp` INTEGER NOT NULL DEFAULT 0,
    `max_sp` INTEGER NOT NULL DEFAULT 0,
    `sp` INTEGER NOT NULL DEFAULT 0,
    `max_ap` INTEGER NOT NULL DEFAULT 0,
    `ap` INTEGER NOT NULL DEFAULT 0,
    `status_point` INTEGER NOT NULL DEFAULT 0,
    `skill_point` INTEGER NOT NULL DEFAULT 0,
    `trait_point` INTEGER NOT NULL DEFAULT 0,
    `option` INTEGER NOT NULL DEFAULT 0,
    `karma` INTEGER NOT NULL DEFAULT 0,
    `manner` INTEGER NOT NULL DEFAULT 0,
    `party_id` INTEGER NOT NULL DEFAULT 0,
    `guild_id` INTEGER NOT NULL DEFAULT 0,
    `pet_id` INTEGER NOT NULL DEFAULT 0,
    `homun_id` INTEGER NOT NULL DEFAULT 0,
    `elemental_id` INTEGER NOT NULL DEFAULT 0,
    `hair` INTEGER NOT NULL DEFAULT 0,
    `hair_color` INTEGER NOT NULL DEFAULT 0,
    `clothes_color` INTEGER NOT NULL DEFAULT 0,
    `body` INTEGER NOT NULL DEFAULT 0,
    `weapon` INTEGER NOT NULL DEFAULT 0,
    `shield` INTEGER NOT NULL DEFAULT 0,
    `head_top` INTEGER NOT NULL DEFAULT 0,
    `head_mid` INTEGER NOT NULL DEFAULT 0,
    `head_bottom` INTEGER NOT NULL DEFAULT 0,
    `robe` INTEGER NOT NULL DEFAULT 0,
    `last_map` VARCHAR(191) NULL,
    `last_x` INTEGER NOT NULL DEFAULT 53,
    `last_y` INTEGER NOT NULL DEFAULT 111,
    `last_instanceid` INTEGER NOT NULL DEFAULT 0,
    `save_map` VARCHAR(191) NULL,
    `save_x` INTEGER NOT NULL DEFAULT 53,
    `save_y` INTEGER NOT NULL DEFAULT 111,
    `partner_id` INTEGER NOT NULL DEFAULT 0,
    `online` INTEGER NOT NULL DEFAULT 0,
    `father` INTEGER NOT NULL DEFAULT 0,
    `mother` INTEGER NOT NULL DEFAULT 0,
    `child` INTEGER NOT NULL DEFAULT 0,
    `fame` INTEGER NOT NULL DEFAULT 0,
    `rename` INTEGER NOT NULL DEFAULT 0,
    `delete_date` INTEGER NOT NULL DEFAULT 0,
    `moves` INTEGER NOT NULL DEFAULT 0,
    `unban_time` INTEGER NOT NULL DEFAULT 0,
    `font` INTEGER NOT NULL DEFAULT 0,
    `uniqueitem_counter` INTEGER NOT NULL DEFAULT 0,
    `sex` ENUM('M', 'F', 'S') NOT NULL DEFAULT 'M',
    `hotkey_rowshift` INTEGER NOT NULL DEFAULT 0,
    `hotkey_rowshift2` INTEGER NOT NULL DEFAULT 0,
    `clan_id` INTEGER NOT NULL DEFAULT 0,
    `last_login` DATETIME(3) NULL,
    `title_id` INTEGER NOT NULL DEFAULT 0,
    `show_equip` INTEGER NOT NULL DEFAULT 0,
    `inventory_slots` INTEGER NOT NULL DEFAULT 100,
    `body_direction` INTEGER NOT NULL DEFAULT 0,
    `disable_call` INTEGER NOT NULL DEFAULT 0,
    `hardmode` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`char_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `mob_db` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name_aegis` VARCHAR(24) NOT NULL,
    `name_english` TEXT NOT NULL,
    `name_japanese` TEXT NULL,
    `monster_image_url` VARCHAR(191) NULL,
    `level` INTEGER NULL,
    `hp` INTEGER NULL,
    `sp` INTEGER NULL,
    `base_exp` INTEGER NULL,
    `job_exp` INTEGER NULL,
    `mvp_exp` INTEGER NULL,
    `attack` INTEGER NULL,
    `attack2` INTEGER NULL,
    `defense` INTEGER NULL,
    `magic_defense` INTEGER NULL,
    `str` INTEGER NULL,
    `agi` INTEGER NULL,
    `vit` INTEGER NULL,
    `int` INTEGER NULL,
    `dex` INTEGER NULL,
    `luk` INTEGER NULL,
    `attack_range` INTEGER NULL,
    `skill_range` INTEGER NULL,
    `chase_range` INTEGER NULL,
    `size` VARCHAR(24) NULL,
    `race` VARCHAR(24) NULL,
    `racegroup_goblin` INTEGER NULL,
    `racegroup_kobold` INTEGER NULL,
    `racegroup_orc` INTEGER NULL,
    `racegroup_golem` INTEGER NULL,
    `racegroup_guardian` INTEGER NULL,
    `racegroup_ninja` INTEGER NULL,
    `racegroup_gvg` INTEGER NULL,
    `racegroup_battlefield` INTEGER NULL,
    `racegroup_treasure` INTEGER NULL,
    `racegroup_biolab` INTEGER NULL,
    `racegroup_manuk` INTEGER NULL,
    `racegroup_splendide` INTEGER NULL,
    `racegroup_scaraba` INTEGER NULL,
    `racegroup_ogh_atk_def` INTEGER NULL,
    `racegroup_ogh_hidden` INTEGER NULL,
    `racegroup_bio5_swordman_thief` INTEGER NULL,
    `racegroup_bio5_acolyte_merchant` INTEGER NULL,
    `racegroup_bio5_mage_archer` INTEGER NULL,
    `racegroup_bio5_mvp` INTEGER NULL,
    `racegroup_clocktower` INTEGER NULL,
    `racegroup_thanatos` INTEGER NULL,
    `racegroup_faceworm` INTEGER NULL,
    `racegroup_hearthunter` INTEGER NULL,
    `racegroup_rockridge` INTEGER NULL,
    `racegroup_werner_lab` INTEGER NULL,
    `racegroup_temple_demon` INTEGER NULL,
    `racegroup_illusion_vampire` INTEGER NULL,
    `racegroup_malangdo` INTEGER NULL,
    `racegroup_ep172alpha` INTEGER NULL,
    `racegroup_ep172beta` INTEGER NULL,
    `racegroup_ep172bath` INTEGER NULL,
    `element` VARCHAR(24) NULL,
    `element_level` INTEGER NULL,
    `walk_speed` INTEGER NULL,
    `attack_delay` INTEGER NULL,
    `attack_motion` INTEGER NULL,
    `damage_motion` INTEGER NULL,
    `damage_taken` INTEGER NULL,
    `ai` VARCHAR(2) NULL,
    `class` VARCHAR(50) NULL,
    `mode_canmove` INTEGER NULL,
    `mode_looter` INTEGER NULL,
    `mode_aggressive` INTEGER NULL,
    `mode_assist` INTEGER NULL,
    `mode_castsensoridle` INTEGER NULL,
    `mode_norandomwalk` INTEGER NULL,
    `mode_nocast` INTEGER NULL,
    `mode_canattack` INTEGER NULL,
    `mode_castsensorchase` INTEGER NULL,
    `mode_changechase` INTEGER NULL,
    `mode_angry` INTEGER NULL,
    `mode_changetargetmelee` INTEGER NULL,
    `mode_changetargetchase` INTEGER NULL,
    `mode_targetweak` INTEGER NULL,
    `mode_randomtarget` INTEGER NULL,
    `mode_ignoremelee` INTEGER NULL,
    `mode_ignoremagic` INTEGER NULL,
    `mode_ignoreranged` INTEGER NULL,
    `mode_mvp` INTEGER NULL,
    `mode_ignoremisc` INTEGER NULL,
    `mode_knockbackimmune` INTEGER NULL,
    `mode_teleportblock` INTEGER NULL,
    `mode_fixeditemdrop` INTEGER NULL,
    `mode_detector` INTEGER NULL,
    `mode_statusimmune` INTEGER NULL,
    `mode_skillimmune` INTEGER NULL,
    `mvpdrop1_item` VARCHAR(50) NULL,
    `mvpdrop1_rate` INTEGER NULL,
    `mvpdrop1_option` VARCHAR(50) NULL,
    `mvpdrop1_index` INTEGER NULL,
    `mvpdrop2_item` VARCHAR(50) NULL,
    `mvpdrop2_rate` INTEGER NULL,
    `mvpdrop2_option` VARCHAR(50) NULL,
    `mvpdrop2_index` INTEGER NULL,
    `mvpdrop3_item` VARCHAR(50) NULL,
    `mvpdrop3_rate` INTEGER NULL,
    `mvpdrop3_option` VARCHAR(50) NULL,
    `mvpdrop3_index` INTEGER NULL,
    `drop1_item` VARCHAR(50) NULL,
    `drop1_rate` INTEGER NULL,
    `drop1_nosteal` INTEGER NULL,
    `drop1_option` VARCHAR(50) NULL,
    `drop1_index` INTEGER NULL,
    `drop2_item` VARCHAR(50) NULL,
    `drop2_rate` INTEGER NULL,
    `drop2_nosteal` INTEGER NULL,
    `drop2_option` VARCHAR(50) NULL,
    `drop2_index` INTEGER NULL,
    `drop3_item` VARCHAR(50) NULL,
    `drop3_rate` INTEGER NULL,
    `drop3_nosteal` INTEGER NULL,
    `drop3_option` VARCHAR(50) NULL,
    `drop3_index` INTEGER NULL,
    `drop4_item` VARCHAR(50) NULL,
    `drop4_rate` INTEGER NULL,
    `drop4_nosteal` INTEGER NULL,
    `drop4_option` VARCHAR(50) NULL,
    `drop4_index` INTEGER NULL,
    `drop5_item` VARCHAR(50) NULL,
    `drop5_rate` INTEGER NULL,
    `drop5_nosteal` INTEGER NULL,
    `drop5_option` VARCHAR(50) NULL,
    `drop5_index` INTEGER NULL,
    `drop6_item` VARCHAR(50) NULL,
    `drop6_rate` INTEGER NULL,
    `drop6_nosteal` INTEGER NULL,
    `drop6_option` VARCHAR(50) NULL,
    `drop6_index` INTEGER NULL,
    `drop7_item` VARCHAR(50) NULL,
    `drop7_rate` INTEGER NULL,
    `drop7_nosteal` INTEGER NULL,
    `drop7_option` VARCHAR(50) NULL,
    `drop7_index` INTEGER NULL,
    `drop8_item` VARCHAR(50) NULL,
    `drop8_rate` INTEGER NULL,
    `drop8_nosteal` INTEGER NULL,
    `drop8_option` VARCHAR(50) NULL,
    `drop8_index` INTEGER NULL,
    `drop9_item` VARCHAR(50) NULL,
    `drop9_rate` INTEGER NULL,
    `drop9_nosteal` INTEGER NULL,
    `drop9_option` VARCHAR(50) NULL,
    `drop9_index` INTEGER NULL,
    `drop10_item` VARCHAR(50) NULL,
    `drop10_rate` INTEGER NULL,
    `drop10_nosteal` INTEGER NULL,
    `drop10_option` VARCHAR(50) NULL,
    `drop10_index` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `character` ADD CONSTRAINT `character_class_fkey` FOREIGN KEY (`class`) REFERENCES `character_class`(`class_id`) ON DELETE RESTRICT ON UPDATE CASCADE;
